notifications:
  - provider: Webhook
    url: https://webhook.commit-email.info/

version: "{build}"
clone_depth: 10
environment:
  matrix:
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.1.38
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.1.38
      MROONGA_PLATFORM: "winx64"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.2.21
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.2.21
      MROONGA_PLATFORM: "winx64"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.3.12
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.3.12
      MROONGA_PLATFORM: "winx64"

install:
  - cd ..
  - choco install -y curl 7zip.commandline
  - curl -O http://ftp.osuosl.org/pub/mariadb/mariadb-%MARIADB_VERSION%/source/mariadb-%MARIADB_VERSION%.tar.gz
  - 7z x mariadb-%MARIADB_VERSION%.tar.gz
  - 7z x mariadb-%MARIADB_VERSION%.tar > nul
  - cd mariadb-%MARIADB_VERSION%
  - rmdir /S /Q storage\mroonga\
  - ps: Get-Content ..\mroonga\version | ForEach-Object { $env:MROONGA_VERSION = $_ }
  - move ..\mroonga storage\mroonga
  - git clone --quiet --depth 1 --recursive https://github.com/groonga/groonga.git ..\groonga
  - ps: Get-Content ..\groonga\base_version | ForEach-Object { $env:GROONGA_VERSION = $_ }
  - rmdir /S /Q ..\groonga\test\
  - cd ..\groonga\vendor
  - c:\Ruby26-x64\bin\ruby -v download_lz4.rb
  - c:\Ruby26-x64\bin\ruby -v download_mecab.rb
  - c:\Ruby26-x64\bin\ruby -v download_message_pack.rb
  - cd ..\..\mariadb-%MARIADB_VERSION%
  - mkdir storage\mroonga\vendor
  - move ..\groonga storage\mroonga\vendor\groonga
  - git clone --quiet --depth 1 https://github.com/groonga/groonga-normalizer-mysql.git storage\mroonga\vendor\groonga\vendor\plugins\groonga-normalizer-mysql

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%"
  - set MSYSTEM=MINGW64
  - pacman -Sy --noconfirm bison
  - move mariadb-%MARIADB_VERSION% source
  - mkdir build
  - cd build
  - cmake ..\source -G "%CMAKE_GENERATOR_NAME%"
      -DMRN_GROONGA_EMBED=OFF
      -DMRN_GROONGA_NORMALIZER_MYSQL_EMBED=OFF
      -DGRN_WITH_BUNDLED_LZ4=ON
      -DGRN_WITH_BUNDLED_MECAB=ON
      -DGRN_WITH_BUNDLED_MESSAGE_PACK=ON
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmake --build . --config RelWithDebInfo
  - cmake --build . --config RelWithDebInfo --target package
  - move *.zip ..\
  - cd ..\
  - 7z x mariadb-%MARIADB_VERSION%-%MROONGA_PLATFORM%.zip
  - netsh advfirewall firewall add rule
      name="mariadb"
      dir=in
      action=allow
      protocol=TCP
      localport=3306
      enable=yes
      profile=any
  - ps: .\source\storage\mroonga\packages\windows\install-mroonga.ps1
      -mariadbVersion $env:MARIADB_VERSION
      -platform $env:MROONGA_PLATFORM

test: off

on_success:
  - 7z a mariadb-%MARIADB_VERSION%-with-mroonga-%MROONGA_VERSION%-%MROONGA_PLATFORM%.zip
         mariadb-%MARIADB_VERSION%-%MROONGA_PLATFORM%
  - set ARTIFACT=mariadb-%MARIADB_VERSION%-with-mroonga-%MROONGA_VERSION%-%MROONGA_PLATFORM%.zip
  - ps: Push-AppveyorArtifact $Env:ARTIFACT
