notifications:
  - provider: Webhook
    url: https://webhook.commit-email.info/

version: "{build}"
clone_depth: 10
configuration:
  - BuildCheck
  - ReleasePackage
environment:
  matrix:
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.1.38
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.1.38
      MROONGA_PLATFORM: "winx64"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.2.21
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.2.21
      MROONGA_PLATFORM: "winx64"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.3.12
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.3.12
      MROONGA_PLATFORM: "winx64"

matrix:
  exclude:
    - configuration: ReleasePackage
      MARIADB_VERSION: 10.1.38
    - configuration: ReleasePackage
      MARIADB_VERSION: 10.2.21

install:
  - cd ..
  - choco install -y curl 7zip.commandline
  - curl -O http://ftp.osuosl.org/pub/mariadb/mariadb-%MARIADB_VERSION%/source/mariadb-%MARIADB_VERSION%.tar.gz
  - 7z x mariadb-%MARIADB_VERSION%.tar.gz
  - 7z x mariadb-%MARIADB_VERSION%.tar > nul
  - cd mariadb-%MARIADB_VERSION%
  - rmdir /S /Q storage\mroonga\
  - ps: Get-Content ..\mroonga\version | ForEach-Object { $env:MROONGA_VERSION = $_ }
  - move ..\mroonga storage\mroonga
  - git clone --quiet --depth 1 --recursive https://github.com/groonga/groonga.git ..\groonga
  - ps: Get-Content ..\groonga\base_version | ForEach-Object { $env:GROONGA_VERSION = $_ }
  - ps: Get-Content ..\groonga\include\groonga\version.h.in | ForEach-Object { $_ -replace "@GRN_VERSION@","$env:GROONGA_VERSION" } | Set-Content ..\groonga\include\groonga\version.h
  - rmdir /S /Q ..\groonga\test\
  - cd ..\groonga\vendor
  - c:\Ruby26-x64\bin\ruby -v download_lz4.rb
  - c:\Ruby26-x64\bin\ruby -v download_mecab.rb
  - cd ..\..\mariadb-%MARIADB_VERSION%
  - mkdir storage\mroonga\vendor
  - move ..\groonga storage\mroonga\vendor\groonga
  - git clone --quiet --depth 1 https://github.com/groonga/groonga-normalizer-mysql.git storage\mroonga\vendor\groonga\vendor\plugins\groonga-normalizer-mysql
test: off

for:
  -
    matrix:
      only:
        - configuration: BuildCheck
    build_script:
      - "echo # > win\\packaging\\CMakeLists.txt"
      - cmake . -G "%CMAKE_GENERATOR_NAME%"
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DPLUGIN_ARCHIVE=NO
          -DPLUGIN_BLACKHOLE=NO
          -DPLUGIN_CASSANDRA=NO
          -DPLUGIN_CONNECT=NO
          -DPLUGIN_CSV=NO
          -DPLUGIN_EXAMPLE=NO
          -DPLUGIN_FEDERATED=NO
          -DPLUGIN_FEDERATEDX=NO
          -DPLUGIN_HEAP=NO
          -DPLUGIN_INNOBASE=YES
          -DPLUGIN_MYISAM=NO
          -DPLUGIN_MYISAMMRG=NO
          -DPLUGIN_OQGRAPH=NO
          -DPLUGIN_PERFSCHEMA=NO
          -DPLUGIN_SEQUENCE=NO
          -DPLUGIN_SPHINX=NO
          -DPLUGIN_SPIDER=NO
          -DPLUGIN_TEST_SQL_DISCOVERY=NO
          -DPLUGIN_TOKUDB=NO
          -DPLUGIN_XTRADB=NO
          -DWITH_UNIT_TESTS=OFF
          -DWITH_MARIABACKUP=OFF
          -DGRN_WITH_BUNDLED_MECAB=ON
      - cmake --build . --config RelWithDebInfo
  -
    matrix:
      only:
        - configuration: ReleasePackage
    build_script:
      - set
      - cd %APPVEYOR_BUILD_FOLDER%\..
      - git clone --depth 1
        https://github.com/cosmo0920/PowerShell-for-Mroonga-building.git mrnbuild
      - cd mrnbuild/powershell
      - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%"
      - set MSYSTEM=MINGW64
      - pacman -Sy --noconfirm bison
      - ps: .\get-mroonga-batfiles.ps1
      - ps: .\prepare-building-mroonga.ps1
      - cmake --version
      - bison --version
      - move ..\..\mariadb-%MARIADB_VERSION% work/source
      - cd .\work
      - if %MROONGA_PLATFORM% == "win32" call .\build-vc2015-zip-32.bat
      - if %MROONGA_PLATFORM% == "winx64" call .\build-vc2015-zip-64.bat
      - 7z x mariadb-%MARIADB_VERSION%-%MROONGA_PLATFORM%.zip
      - cd ..\
      - netsh advfirewall firewall add rule name="mariadb" dir=in action=allow protocol=TCP localport=3306 enable=yes profile=any
      - ps: .\install-mroonga.ps1 -mariadbVersion %MARIADB_VERSION% -platforms %MROONGA_PLATFORM%
      - ps: .\create-mrnzip.ps1 -mariadbVersion %MARIADB_VERSION% -mroongaVersion %MROONGA_VERSION% -platforms %MROONGA_PLATFORM%
    on_success:
      - pwd
      - set ARTIFACT=work\mariadb-%MARIADB_VERSION%-with-mroonga-%MROONGA_VERSION%-%MROONGA_PLATFORM%.zip
      - ps: Push-AppveyorArtifact $Env:ARTIFACT
