notifications:
  - provider: Webhook
    url: https://webhook.commit-email.info/

version: "{build}"
clone_depth: 10
environment:
  matrix:
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.1.38
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.1.38
      MROONGA_PLATFORM: "winx64"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.2.21
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.2.21
      MROONGA_PLATFORM: "winx64"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      MARIADB_VERSION: 10.3.12
      MROONGA_PLATFORM: "win32"
    - CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      MARIADB_VERSION: 10.3.12
      MROONGA_PLATFORM: "winx64"

install:
  - cd ..
  - choco install -y curl 7zip.commandline
  - curl -O http://ftp.osuosl.org/pub/mariadb/mariadb-%MARIADB_VERSION%/source/mariadb-%MARIADB_VERSION%.tar.gz
  - 7z x mariadb-%MARIADB_VERSION%.tar.gz
  - 7z x mariadb-%MARIADB_VERSION%.tar > nul
  - cd mariadb-%MARIADB_VERSION%
  - rmdir /S /Q storage\mroonga\
  - ps: Get-Content ..\mroonga\version | ForEach-Object { $env:MROONGA_VERSION = $_ }
  - move ..\mroonga storage\mroonga
  - git clone --quiet --depth 1 --recursive https://github.com/groonga/groonga.git ..\groonga
  - ps: Get-Content ..\groonga\base_version | ForEach-Object { $env:GROONGA_VERSION = $_ }
#  - ps: Get-Content ..\groonga\include\groonga\version.h.in | ForEach-Object { $_ -replace "@GRN_VERSION@","$env:GROONGA_VERSION" } | Set-Content ..\groonga\include\groonga\version.h
  - rmdir /S /Q ..\groonga\test\
  - cd ..\groonga\vendor
  - c:\Ruby26-x64\bin\ruby -v download_lz4.rb
  - c:\Ruby26-x64\bin\ruby -v download_mecab.rb
  - cd ..\..\mariadb-%MARIADB_VERSION%
  - mkdir storage\mroonga\vendor
  - move ..\groonga storage\mroonga\vendor\groonga
  - git clone --quiet --depth 1 https://github.com/groonga/groonga-normalizer-mysql.git storage\mroonga\vendor\groonga\vendor\plugins\groonga-normalizer-mysql
test: off

build_script:
  - set
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - dir
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%"
  - set MSYSTEM=MINGW64
  - pacman -Sy --noconfirm bison
  - cmake --version
  - bison --version
  - cd mariadb-%MARIADB_VERSION%
  - if "%MROONGA_PLATFORM%" == "win32" call .\mariadb-%MARIADB_VERSION%\storage\mroonga\packages\windows\build-vc2015-zip-32.bat
  - if "%MROONGA_PLATFORM%" == "winx64" call .\mariadb-%MARIADB_VERSION%\storage\mroonga\packages\windows\build-vc2015-zip-64.bat
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - 7z x mariadb-%MARIADB_VERSION%-%MROONGA_PLATFORM%.zip
  - cd ..\
  - netsh advfirewall firewall add rule name="mariadb" dir=in action=allow protocol=TCP localport=3306 enable=yes profile=any
  - set MROONGA_INSTALL_SCRIPT=.\mariadb-%MARIADB_VERSION%\packages/windows/install-mroonga.ps1
  - set PACKAGE_BASE_DIR=.\mariadb-%MARIADB_VERSION%-%MROONGA_PLATFORM%
  - ps: $env:MROONGA_INSTALL_SCRIPT -workDir $env:PACKAGE_BASE_DIR .\mariadb -mariadbVersion $env:MARIADB_VERSION -platforms $env:MROONGA_PLATFORM
on_success:
  - pwd
  - 7z a mariadb-%MARIADB_VERSION%-with-%MROONGA_VERSION-%MROONGA_PLATFORM%.zip mariadb-%MARIADB_VERSION%-%MROONGA_PLATFORM%
  - set ARTIFACT=work\mariadb-%MARIADB_VERSION%-with-mroonga-%MROONGA_VERSION%-%MROONGA_PLATFORM%.zip
  - ps: Push-AppveyorArtifact $Env:ARTIFACT
